language: csharp
dotnet: 2.1.500
mono: 5.14.0
script:
  - dotnet restore
  - dotnet build ./PrizmaPlatform.sln --configuration Release
  - dotnet test ./Domain.Models.Tests/Domain.Models.Tests.csproj
  - dotnet test ./Domain.Services.Tests/Domain.Services.Tests.csproj
  - dotnet test ./API.Services.Tests/API.Services.Tests.csproj
