language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
script:
  - dotnet restore
  - dotnet build ./PrizmaPlatform.sln --configuration Release
  - dotnet test ./Domain.Models.Tests/Domain.Models.Tests.csproj
  - dotnet test ./Domain.Services.Tests/Domain.Services.Tests.csproj
  - dotnet test ./API.Services.Tests/API.Services.Tests.csproj
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1